### PR TITLE
new project added

### PR DESCRIPTION
**Pull request by shailifadadu**
Created the small website using HTML and CSS

### CODE REVIEW

**Comment by shailifadadu** [comment]
Hey @pranitrathod I'm done with the work u assigned me. Can u plz review my PR!!

**Comment by pranitrathod** [comment]
Thanks @shailifadadu I'll review it!

**Comment by pranitrathod** [comment]
Hello @shailifadadu by reviewing your code my team said your IMAGES are not rendering properly

**Comment by shailifadadu** [comment]
@pranitrathod  I'm able to watch the images properly!!

**Comment by pranitrathod** [comment]
One of my mate, acknowledge this mistake
I'll review it myself and will fix it
@shailifadadu

**Comment by pranitrathod** [comment]
There's a conflict in your PR as well @shailifadadu I'll fix it

**Comment by shailifadadu** [comment]
Okays👍

**Comment by shailifadadu** [comment]
Okay 👍

**Comment by shailifadadu** [comment]
@pranitrathod  Can u add Hacktoberfest accepted label??

**Comment by pranitrathod** [comment]
You don't have to write inside issue section we maintainer do check everything
@shailifadadu and please understand that "THE TAG" you  referring is already been tag on this repo
Go to my my this repo>About section>tags
there you'll find hacktoberfest , hacktoberfest- accepted we never tag such names on issues rather then bug,doc/ goodIssue

Thank you!

**Comment by shailifadadu** [comment]
Okay thanks got it 👍

**Pull request merged**
